/*
 *  This file is part of AndroidIDE.
 *
 *  AndroidIDE is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  AndroidIDE is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *   along with AndroidIDE.  If not, see <https://www.gnu.org/licenses/>.
 */

package org.appdevforall.codeonthego.uidesigner


import com.itsaky.androidide.uidesigner.R
import android.os.Bundle
import android.view.View
import android.view.ViewGroup
import android.view.ViewGroup.LayoutParams.MATCH_PARENT
import org.appdevforall.codeonthego.app.BaseIDEActivity
import org.appdevforall.codeonthego.editor.language.treesitter.XMLLanguage
import org.appdevforall.codeonthego.editor.schemes.IDEColorSchemeProvider
import org.appdevforall.codeonthego.editor.ui.IDEEditor
import org.appdevforall.codeonthego.preferences.internal.EditorPreferences
import org.appdevforall.codeonthego.syntax.colorschemes.SchemeAndroidIDE
import com.itsaky.androidide.uidesigner.databinding.ActivityShowXmlBinding
import org.appdevforall.codeonthego.utils.flashInfo
import org.appdevforall.codeonthego.utils.jetbrainsMono
import io.github.rosemoe.sora.event.Unsubscribe
import io.github.rosemoe.sora.widget.CodeEditor
import org.slf4j.LoggerFactory

/**
 * An activity to show the XML code generated by UI Designer.
 *
 * @author Akash Yadav
 */
class ShowXmlActivity : BaseIDEActivity() {

  private var editor: CodeEditor? = null
  private var unsubscribe: Unsubscribe? = null
  private var binding: ActivityShowXmlBinding? = null

  companion object {

    private val log = LoggerFactory.getLogger(ShowXmlActivity::class.java)

    const val KEY_XML = "ide.uidesigner.viewXml.Xml"
  }

  override fun bindLayout(): View {
    this.binding = ActivityShowXmlBinding.inflate(layoutInflater)
    this.editor = IDEEditor(this)

    setSupportActionBar(this.binding!!.toolbar)
    supportActionBar?.setDisplayHomeAsUpEnabled(true)

    this.binding!!.toolbar.setNavigationOnClickListener { finish() }

    this.editor?.let { editor ->
      editor.colorScheme = SchemeAndroidIDE.newInstance(this@ShowXmlActivity)
      editor.editable = false
      editor.typefaceText = jetbrainsMono()
      editor.typefaceLineNumber = jetbrainsMono()
      editor.setText(intent?.getStringExtra(KEY_XML) ?: "")
      editor.setTextSize(EditorPreferences.fontSize)

      IDEColorSchemeProvider.readSchemeAsync(
        context = this,
        coroutineScope = activityScope,
        type = XMLLanguage.TS_TYPE
      ) {
        if (it == null) {
          log.error("Unable to load color sheme")
          return@readSchemeAsync
        }

        editor.colorScheme = it
        editor.setEditorLanguage(XMLLanguage(this))
      }

      binding!!.editorContainer.let { container ->
        container.removeAllViews()
        container.addView(editor, ViewGroup.LayoutParams(MATCH_PARENT, MATCH_PARENT))
      }
    }

    this.binding?.copy?.setOnClickListener {
      this.editor?.copyText(false)
      flashInfo(R.string.copied)
    }

    return this.binding!!.root
  }

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
  }

  override fun onDestroy() {
    super.onDestroy()
    this.binding = null
    this.unsubscribe?.unsubscribe()
    this.editor?.release()
    this.editor = null
  }
}
