package com.itsaky.androidide.idetooltips

object TooltipTag {
    const val BUILD_VARIANT_SIDEBAR = "project.sidebar.buildvariants"
    const val CLOSE_PROJECT_SIDEBAR = "project.sidebar.closeproject"
    const val FILE_TREE_SIDEBAR = "project.sidebar.filetree"
    const val HELP_SIDEBAR = "project.help"
    const val PREFERENCES_SIDEBAR = "main.prefs"
    const val TERMINAL_SIDEBAR = "project.sidebar.terminal"
    const val EDITOR_TOOLBAR_CODE_ACTIONS = "editor.toolbar.codeactions"
    const val EDITOR_TOOLBAR_COPY = "editor.toolbar.copy"
    const val EDITOR_TOOLBAR_CUT = "editor.toolbar.cut"
    const val EDITOR_TOOLBAR_EXPAND_SELECTION = "editor.toolbar.expandselection"
    const val EDITOR_TOOLBAR_LONG_SELECT = "editor.toolbar.longselect"
    const val EDITOR_TOOLBAR_PASTE = "editor.toolbar.paste"
    const val EDITOR_TOOLBAR_SELECT_ALL = "editor.toolbar.selectall"
    const val EDITOR_TOOLBAR_HELP = "editor.toolbar.help"
    const val PROJECT_APP_LOGS = "project.applogs"
    const val PROJECT_IDE_LOGS = "project.idelogs"
    const val PROJECT_SEARCH_RESULTS = "project.searchresults"
    const val PROJECT_DIAGNOSTICS = "project.diagnostics"
    const val PROJECT_GRADLE_TASKS = "project.gradle.tasks"

    // General Preferences
    const val PREFS_EDITOR = "prefs.editor"
    const val PREFS_GENERAL = "prefs.general"
    const val PREFS_BUILD_RUN = "prefs.buildrun"
    const val PREFS_TERMUX = "prefs.termux"

    const val PROJECT_OVERVIEW_TEXT = "project.overview"
    const val EDITOR_PROJECT_OVERVIEW = "project.overview"
    const val EDITOR_TOOLTIP_NAV_ICON = "project.menu"
    const val EDITOR_TOOLBAR_QUICK_RUN = "project.run"
    const val EDITOR_TOOLBAR_DEBUG = "project.debug"
    const val EDITOR_TOOLBAR_RUN_TASKS = "project.gradle.tasks"
    const val EDITOR_TOOLBAR_FIND = "project.find.top"
    const val EDITOR_TOOLBAR_FIND_IN_PROJECT = "project.find.in.project"
    const val EDITOR_TOOLBAR_SYNC = "project.sync"
    const val EDITOR_TOOLBAR_LAUNCH_APP = "project.launch.app"
    const val EDITOR_BUILD_STATUS = "project.status"
}