package com.itsaky.androidide.idetooltips

object TooltipTag {
    const val BUILD_VARIANT_SIDEBAR = "project.sidebar.buildvariants"
    const val CLOSE_PROJECT_SIDEBAR = "project.sidebar.closeproject"
    const val FILE_TREE_SIDEBAR = "project.sidebar.filetree"
    const val HELP_SIDEBAR = "project.help"
    const val PREFERENCES_SIDEBAR = "main.prefs"
    const val TERMINAL_SIDEBAR = "project.sidebar.terminal"
    const val EDITOR_TOOLBAR_CODE_ACTIONS = "editor.toolbar.codeactions"
    const val EDITOR_TOOLBAR_COPY = "editor.toolbar.copy"
    const val EDITOR_TOOLBAR_CUT = "editor.toolbar.cut"
    const val EDITOR_TOOLBAR_EXPAND_SELECTION = "editor.toolbar.expandselection"
    const val EDITOR_TOOLBAR_LONG_SELECT = "editor.toolbar.longselect"
    const val EDITOR_TOOLBAR_PASTE = "editor.toolbar.paste"
    const val EDITOR_TOOLBAR_SELECT_ALL = "editor.toolbar.selectall"
    const val EDITOR_TOOLBAR_HELP = "editor.toolbar.help"
    const val PROJECT_APP_LOGS = "project.applogs"
    const val PROJECT_IDE_LOGS = "project.idelogs"
    const val PROJECT_SEARCH_RESULTS = "project.searchresults"
    const val PROJECT_DIAGNOSTICS = "project.diagnostics"

    // Code Actions menu
    const val EDITOR_CODEACTIONS_COMMENT = "editor.codeactions.comment"
    const val EDITOR_CODEACTIONS_UNCOMMENT = "editor.codeactions.uncomment"
    const val EDITOR_CODEACTIONS_GOTODEF = "editor.codeactions.gotodef"
    const val EDITOR_CODEACTIONS_FINDREFS = "editor.codeactions.findrefs"
    const val EDITOR_CODEACTIONS_FIXIMPORTS = "editor.codeactions.fiximports"
    const val EDITOR_CODEACTIONS_SETTERGETTER = "editor.codeactions.settergetter"
    const val EDITOR_CODEACTIONS_SETTERGETTER_DIALOG = "editor.codeactions.settergetter.dialog"
    const val EDITOR_CODEACTIONS_OVERRIDESUPER = "editor.codeactions.overridesuper"
    const val EDITOR_CODEACTIONS_OVERRIDESUPER_DIALOG = "editor.codeactions.overridesuper.dialog"
    const val EDITOR_CODEACTIONS_GENCONSTRUCTOR = "editor.codeactions.genconstructor"
    const val EDITOR_CODEACTIONS_GENCONSTRUCTOR_DIALOG = "editor.codeactions.genconstructor.dialog"
    const val EDITOR_CODEACTIONS_GENTOSTRING = "editor.codeactions.gentostring"
    const val EDITOR_CODEACTIONS_GENTOSTRING_DIALOG = "editor.codeactions.gentostring.dialog"
    const val EDITOR_CODEACTIONS_UNUSEDIMPORTS = "editor.codeactions.unusedimports"
    const val EDITOR_CODEACTIONS_ORGANIZEIMPORTS = "editor.codeactions.organizeimports"

}