[versions]
activityKtx = "1.8.2"
agp = "8.8.2"
agp-tooling = "8.11.0"
androidSpinkit = "1.4.0"
appcompat = "1.6.1"
colorpickerview = "2.3.0"
commonsCompress = "1.27.1"
commonsText = "1.11.0"
commonsTextVersion = "1.14.0"
constraintlayout = "2.1.4"
coreKtx = "1.12.0"
firebaseBom = "34.0.0"
gradle-tooling = "8.6"
gson = "2.10.1"
junit-jupiter = "5.10.2"
anroidx-test-core = "2.2.0"
kotlin = "2.1.21"
kotlin-coroutines = "1.9.0"
lifecycleViewmodelKtx = "2.7.0"
paletteKtx = "1.0.0"
playServicesOssLicenses = "17.1.0"
preferenceKtxVersion = "1.2.1"
recyclerview = "1.3.2"
tree-sitter = "4.3.1"
editor = "0.23.6"
glide = "4.16.0"
androidx-vectordrawable = "1.2.0"
androidx-navigation = "2.7.7"
ksp = "2.1.21-2.0.2"
antlr4 = "4.13.1"
androidx-work = "2.10.0"
androidx-espresso = "3.5.1"
retrofit = "2.11.0"
markwon = "4.6.2"
maven-publish-plugin = "0.27.0"
logback = "1.5.3"
room = "2.7.2"
utilcodex = "1.31.1"
viewpager2 = "1.1.0-beta02"
zoomage = "1.3.1"
monitor = "1.6.1"
monitorVersion = "1.7.2"

## IMPORTANT!
## When updating this value, please manually compile libbrotli.so from Brotli4j for Android and
## put it in app/src/main/jniLibs
brotli4j = "1.18.0"
spotless = "7.2.1"

[libraries]

# Dependencies in composite build
android-spinkit = { module = "com.github.ybq:Android-SpinKit", version.ref = "androidSpinkit" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout-v214 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx-v1120 = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "paletteKtx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtxVersion" }
androidx-recyclerview-v132 = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-viewpager2-v110beta02 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
colorpickerview = { module = "com.github.skydoves:colorpickerview", version.ref = "colorpickerview" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commonsCompress" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commonsText" }
commons-text-v1140 = { module = "org.apache.commons:commons-text", version.ref = "commonsTextVersion" }
composite-appintro = { module = "com.itsaky.androidide.build:appintro" }
composite-constants = { module = "com.itsaky.androidide.build:constants" }
composite-desugaringCore = { module = "com.itsaky.androidide.build:desugaring-core" }
composite-fuzzysearch = { module = "com.itsaky.androidide.build:fuzzysearch" }
composite-googleJavaFormat = { module = "com.itsaky.androidide.build:google-java-format" }
composite-javac = { module = "com.itsaky.androidide.build:javac" }
composite-javapoet = { module = "com.itsaky.androidide.build:javapoet" }
composite-jaxp = { module = "com.itsaky.androidide.build:jaxp" }
composite-jdt = { module = "com.itsaky.androidide.build:jdt" }
composite-layoutlibApi = { module = "com.itsaky.androidide.build:layoutlib-api" }
composite-treeview = { module = "com.itsaky.androidide.build:treeview" }

# Room
firebase-ai = { module = "com.google.firebase:firebase-ai" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
gson-v2101 = { module = "com.google.code.gson:gson", version.ref = "gson" }
play-services-oss-licenses = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "playServicesOssLicenses" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }


# AndroidIDE
androidide-ts = { module = "com.itsaky.androidide.treesitter:android-tree-sitter", version.ref = "tree-sitter" }
androidide-ts-java = { module = "com.itsaky.androidide.treesitter:tree-sitter-java", version.ref = "tree-sitter" }
androidide-ts-json = { module = "com.itsaky.androidide.treesitter:tree-sitter-json", version.ref = "tree-sitter" }
androidide-ts-kotlin = { module = "com.itsaky.androidide.treesitter:tree-sitter-kotlin", version.ref = "tree-sitter" }
androidide-ts-log = { module = "com.itsaky.androidide.treesitter:tree-sitter-log", version.ref = "tree-sitter" }
androidide-ts-xml = { module = "com.itsaky.androidide.treesitter:tree-sitter-xml", version.ref = "tree-sitter" }

#Layout Editor
utilcodex = { module = "com.blankj:utilcodex", version.ref = "utilcodex" }
zoomage = { module = "com.jsibbold:zoomage", version.ref = "zoomage" }
sora-bom = { module = "io.github.Rosemoe.sora-editor:bom", version.ref = "editor" }
sora-language-textmate = { module = "io.github.Rosemoe.sora-editor:language-textmate" }

# Common
common-editor = { module = "io.github.Rosemoe.sora-editor:editor" }
common-utilcode = { module = "com.blankj:utilcodex", version = "1.31.1" }
common-glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
common-glide_ap = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
common-jsoup = { module = "org.jsoup:jsoup", version = "1.19.1" }
common-antlr4 = { module = "org.antlr:antlr4", version.ref = "antlr4" }
common-antlr4-runtime = { module = "org.antlr:antlr4-runtime", version.ref = "antlr4" }
common-javaparser = { module = "com.github.javaparser:javaparser-symbol-solver-core", version = "3.25.8" }
common-lang3 = { module = "org.apache.commons:commons-lang3", version = "3.14.0" }
common-io = { module = "commons-io:commons-io", version = "2.15.1" }
common-kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
common-kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
common-jkotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
common-javapoet = { module = "com.squareup:javapoet", version = "1.13.0" }
common-ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
common-jsonrpc = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc", version = "0.22.0" }
common-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
common-retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
common-markwon-core = { module = "io.noties.markwon:core", version.ref = "markwon" }
common-markwon-extStrikethrough = { module = "io.noties.markwon:ext-strikethrough", version.ref = "markwon" }
common-markwon-linkify = { module = "io.noties.markwon:linkify", version.ref = "markwon" }
common-markwon-recycler = { module = "io.noties.markwon:recycler", version.ref = "markwon" }
common-hiddenApiBypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version = "6.1" }
common-termuxAmLib = { module = "com.termux:termux-am-library", version = "v2.0.0" }
common-charts = { module = "com.github.AppDevNext:AndroidChart", version = "3.1.0.21" }
brotli4j = { module = "com.aayushatharva.brotli4j:brotli4j", version.ref = "brotli4j" }
brotli4j-linux-x64 = { module = "com.aayushatharva.brotli4j:native-linux-x86_64", version.ref = "brotli4j" }
brotli4j-linux-aarch64 = { module = "com.aayushatharva.brotli4j:native-linux-aarch64", version.ref = "brotli4j" }
brotli4j-windows-x64 = { module = "com.aayushatharva.brotli4j:native-windows-x86_64", version.ref = "brotli4j" }
brotli4j-windows-aarch64 = { module = "com.aayushatharva.brotli4j:native-windows-aarch64", version.ref = "brotli4j" }
brotli4j-osx-x64 = { module = "com.aayushatharva.brotli4j:native-osx-x86_64", version.ref = "brotli4j" }
brotli4j-osx-aarch64 = { module = "com.aayushatharva.brotli4j:native-osx-aarch64", version.ref = "brotli4j" }

# AndroidX
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.9.1" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.0" }
androidx-cardview = { module = "androidx.cardview:cardview", version = "1.0.0" }
androidx-collection = { module = "androidx.collection:collection", version = "1.4.0" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.2.1" }
androidx-coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version = "1.3.0" }
androidx-drawer = { module = "androidx.drawerlayout:drawerlayout", version = "1.2.0" }
androidx-grid = { module = "androidx.gridlayout:gridlayout", version = "1.0.0" }
androidx-preference = { module = "androidx.preference:preference", version = "1.2.1" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.4.0" }
androidx-vectors = { module = "androidx.vectordrawable:vectordrawable", version.ref = "androidx-vectordrawable" }
androidx-animated_vectors = { module = "androidx.vectordrawable:vectordrawable-animated", version.ref = "androidx-vectordrawable" }
androidx-core = { module = "androidx.core:core", version = "1.13.1" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.13.1" }
androidx-fragment_ktx = { module = "androidx.fragment:fragment-ktx", version = "1.6.2" }
androidx-libDesugaring = { module = "com.android.tools:desugar_jdk_libs", version = "2.0.4" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.1" }
androidx-transition = { module = "androidx.transition:transition-ktx", version = "1.5.1" }
androidx-nav-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version = "2.8.8" }
androidx-nav-ui = { module = "androidx.navigation:navigation-ui-ktx", version = "2.8.8" }
androidx-tracing = { module = "androidx.tracing:tracing", version = "1.2.0" }
androidx-tracing-ktx = { module = "androidx.tracing:tracing-ktx", version = "1.2.0" }
androidx-viewpager = { module = "androidx.viewpager:viewpager", version = "1.0.0" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version = "1.0.0" }
#noinspection GradleDependency
androidx-window-v1alpha9 = { module = "androidx.window:window", version = "1.0.0-alpha09" }
androidx-work = { module = "androidx.work:work-runtime", version.ref = "androidx-work" }
androidx-work-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }

# Google
google-material = { module = "com.google.android.material:material", version = "1.12.0" }
google-gson = { module = "com.google.code.gson:gson", version = "2.12.1" }
google-guava = { module = "com.google.guava:guava", version = "33.4.0-android" }
google-auto-value-annotations = { module = "com.google.auto.value:auto-value-annotations", version = "1.10.4" }
google-auto-value-ap = { module = "com.google.auto.value:auto-value", version = "1.10.4" }
google-auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version = "1.1.1" }
google-auto-service = { module = "com.google.auto.service:auto-service", version = "1.1.1" }
google-protobuf = { module = "com.google.protobuf:protobuf-java", version = "3.25.3" }
google-java-format = { module = "com.google.googlejavaformat:google-java-format", version = "1.20.0" }
google-flexbox = { module = "com.google.android.flexbox:flexbox", version = "3.0.0" }

# AAPT2
aapt2-common = { module = "com.android.tools:common", version = "31.2.2" }
aapt2-annotations = { module = "com.android.tools:annotations", version = "31.2.2" }
aapt2-jb-annotations = { module = "org.jetbrains:annotations", version = "24.1.0" }
aapt2-proto = { module = "com.android.tools.build:aapt2-proto", version = "8.3.0-10880808" }

logging-logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
logging-logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

# XML
xml-xercesImpl = { module = "xerces:xercesImpl", version = "2.12.2" }
xml-apis = { module = "xml-apis:xml-apis", version = "2.0.2" }
xml-remark = { module = "com.kotcrab.remark:remark", version = "1.2.0" }
xml-resolver = { module = "xml-resolver:xml-resolver", version = "1.2" }
xml-jb-annotations = { module = "org.jetbrains:annotations", version = "24.1.0" }

# GIT
git-jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version = "6.8.0.202311291450-r" }

# Tests
tests-junit = { module = "junit:junit", version = "4.13.2" }
tests-junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
tests-junit-platformLauncher = { module = "org.junit.platform:junit-platform-launcher" }
core-tests-anroidx-arch = { module = "androidx.arch.core:core-testing", version.ref = "anroidx-test-core" }
tests-google-truth = { module = "com.google.truth:truth", version = "1.4.1" }
tests-robolectric = { module = "org.robolectric:robolectric", version = "4.11.1" }
tests-androidx-test-core = { module = "androidx.test:core", version = "1.5.0" }
tests-androidx-test-runner = { module = "androidx.test:runner", version = "1.6.2" }
tests-androidx-test-rules = { module = "androidx.test:rules", version = "1.5.0" }
tests-androidx-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
tests-androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "androidx-work" }
tests-androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
tests-androidx-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "androidx-espresso" }
tests-androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version = "2.3.0" }
tests-mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version = "5.2.1" }
tests-mockk = { module = "io.mockk:mockk", version = "1.13.10" }
tests-barista = { module = "com.adevinta.android:barista", version = "4.3.0" }
tests-kaspresso = { module = "com.kaspersky.android-components:kaspresso", version = "1.6.0" }
tests-orchestrator = { module = "androidx.test:orchestrator", version = "1.5.1" }
tests-junit-kts = { module = "androidx.test.ext:junit-ktx", version = "1.2.1" }

# Tooling
tooling-builderModel = { module = "com.android.tools.build:builder-model", version.ref = "agp-tooling" }
tooling-gradleApi = { module = "com.itsaky.androidide.gradle:gradle-tooling-api", version.ref = "gradle-tooling" }
tooling-slf4j = { module = "org.slf4j:slf4j-api", version = "2.0.12" }

# Classpaths
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-plugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
nav-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidx-navigation" }
maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "maven-publish-plugin" }
androidx-monitor = { group = "androidx.test", name = "monitor", version.ref = "monitor" }
monitor = { group = "androidx.test", name = "monitor", version.ref = "monitorVersion" }
org-json = { module = "org.json:json", version = "20210307"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish.base", version.ref = "maven-publish-plugin" }
gradle-publish = { id = "com.gradle.plugin-publish", version = "1.2.1" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }