package com.itsaky.androidide.gradle.quickbuild

/**
 * Emits the Java source of a generated proxy component: a subclass of the user's class
 * whose manifest name stays stable while the user hierarchy swaps. Extension (not
 * delegation) is enough because proxy and user class both travel in the payload dex - a
 * reload swaps the whole hierarchy together (see quick-build/README.md, "Proxy-app
 * architecture"). Per type: activities add the app-switcher gesture hook (plan A3) and a
 * getClassLoader() override so by-name class resolution (Fragment/Navigation destinations,
 * LayoutInflater custom views) can see payload-only classes (ADFA-4128 Bug 9), services
 * register with the runtime's live-service census, receivers and providers are empty
 * subclasses (receivers instantiate fresh per delivery; providers swap by restart).
 */
object ProxySourceGenerator {
	/** Runtime gesture hook the activity proxies call; public entry point of the runtime AAR. */
	private const val GESTURES_CLASS = "com.itsaky.androidide.quickbuild.runtime.QuickBuildGestures"

	/** Runtime live-service census the service proxies report to. */
	private const val SERVICE_TRACKER_CLASS = "com.itsaky.androidide.quickbuild.runtime.ServiceTracker"

	/**
	 * Runtime classloader picker the activity proxies call from their getClassLoader()
	 * override (ADFA-4128 Bug 9 - see QuickBuildClassLoaders' doc for why the override is
	 * needed at all).
	 */
	private const val CLASS_LOADERS_CLASS = "com.itsaky.androidide.quickbuild.runtime.QuickBuildClassLoaders"

	/** Emits the proxy source for [component]; the Application entry has no proxy. */
	fun generateSource(component: ProxiedComponent): String {
		val proxyClass =
			requireNotNull(component.proxyClass) {
				"component '${component.userClass}' of type ${component.type} has no proxy class"
			}
		return generateSource(proxyClass, component.userClass, component.type)
	}

	/**
	 * @param proxyClass fully-qualified proxy class name (must contain a package).
	 * @param userClass fully-qualified user class the proxy extends.
	 */
	fun generateSource(
		proxyClass: String,
		userClass: String,
		type: ComponentType = ComponentType.ACTIVITY,
	): String {
		require('.' in proxyClass) { "proxy class '$proxyClass' has no package" }
		val packageName = proxyClass.substringBeforeLast('.')
		val simpleName = proxyClass.substringAfterLast('.')
		// A nested user class arrives as a BINARY name (Outer$Inner); a Java source
		// `extends` clause needs the CANONICAL name (Outer.Inner), so map '$' to '.'.
		// Proxy names are flat generated identifiers and never carry '$'.
		val userSourceName = userClass.replace('$', '.')
		return buildString {
			append("package ").append(packageName).append(";\n")
			append('\n')
			append("/**\n")
			append(" * Generated by CoGo Quick Build (ADFA-4128). Gives the manifest a stable component\n")
			append(" * name while the user's class stays swappable: proxy and superclass both\n")
			append(" * travel in the payload dex, so a hot reload swaps them together.\n")
			append(" */\n")
			append("public class ")
				.append(simpleName)
				.append(" extends ")
				.append(userSourceName)
				.append(" {\n")
			when (type) {
				ComponentType.ACTIVITY -> {
					appendActivityBody()
				}

				ComponentType.SERVICE -> {
					appendServiceBody()
				}

				ComponentType.RECEIVER, ComponentType.PROVIDER -> {
					Unit
				}

				ComponentType.APPLICATION -> {
					throw IllegalArgumentException("the Application gets no proxy")
				}
			}
			append("}\n")
		}
	}

	private fun StringBuilder.appendActivityBody() {
		append('\n')
		append("\t/**\n")
		append("\t * Quick Build app-switcher gesture (3-finger tap returns to CoGo). The hook only\n")
		append("\t * observes; every event still reaches the app via super, unconsumed and undelayed.\n")
		append("\t */\n")
		append("\t@Override\n")
		append("\tpublic boolean dispatchTouchEvent(android.view.MotionEvent ev) {\n")
		append("\t\t").append(GESTURES_CLASS).append(".onDispatchTouchEvent(this, ev);\n")
		append("\t\treturn super.dispatchTouchEvent(ev);\n")
		append("\t}\n")
		append('\n')
		append("\t/**\n")
		append("\t * ADFA-4128 Bug 9: Context#getClassLoader() is otherwise fixed to the base APK's\n")
		append("\t * classloader regardless of which loader instantiated this activity, so\n")
		append("\t * by-name resolution (LayoutInflater custom views, FragmentFactory/Navigation\n")
		append("\t * destinations) can never see a payload-only class without this override.\n")
		append("\t */\n")
		append("\t@Override\n")
		append("\tpublic ClassLoader getClassLoader() {\n")
		append("\t\treturn ").append(CLASS_LOADERS_CLASS).append(".forActivity(super.getClassLoader());\n")
		append("\t}\n")
	}

	private fun StringBuilder.appendServiceBody() {
		append('\n')
		append("\t/**\n")
		append("\t * Live-service census for the runtime: a restart-based swap needs to know which\n")
		append("\t * services are alive. Observation only - super always runs.\n")
		append("\t */\n")
		append("\t@Override\n")
		append("\tpublic void onCreate() {\n")
		append("\t\tsuper.onCreate();\n")
		append("\t\t").append(SERVICE_TRACKER_CLASS).append(".onServiceCreated(this);\n")
		append("\t}\n")
		append('\n')
		append("\t@Override\n")
		append("\tpublic void onDestroy() {\n")
		append("\t\t").append(SERVICE_TRACKER_CLASS).append(".onServiceDestroyed(this);\n")
		append("\t\tsuper.onDestroy();\n")
		append("\t}\n")
	}
}
