package com.itsaky.androidide.gradle.quickbuild

/**
 * Emits the Java source of a proxy component: a subclass of the user's class that keeps the manifest
 * name stable while the user hierarchy swaps.
 *
 * Extending is enough (no delegation) because proxy and user class both travel in the payload dex,
 * so a reload swaps them together - see quickbuild/README.md, "Proxy-app architecture". Activities
 * add a getClassLoader() override; every other type stays an empty subclass.
 */
object ProxySourceGenerator {
	/**
	 * Runtime classloader picker the activity proxies call from their getClassLoader()
	 * override (see QuickBuildClassLoaders' doc for why the override is
	 * needed at all).
	 */
	private const val CLASS_LOADERS_CLASS = "com.itsaky.androidide.quickbuild.runtime.QuickBuildClassLoaders"

	/**
	 * Every word Java refuses as an identifier: the reserved words plus the three literals,
	 * which are equally illegal in a package or class name.
	 *
	 * `_` and the contextual words (`var`, `record`, `sealed`, `yield`) are deliberately absent:
	 * they are legal identifiers at the positions a proxy source writes them.
	 */
	private val JAVA_RESERVED_WORDS =
		setOf(
			"abstract",
			"assert",
			"boolean",
			"break",
			"byte",
			"case",
			"catch",
			"char",
			"class",
			"const",
			"continue",
			"default",
			"do",
			"double",
			"else",
			"enum",
			"extends",
			"final",
			"finally",
			"float",
			"for",
			"goto",
			"if",
			"implements",
			"import",
			"instanceof",
			"int",
			"interface",
			"long",
			"native",
			"new",
			"package",
			"private",
			"protected",
			"public",
			"return",
			"short",
			"static",
			"strictfp",
			"super",
			"switch",
			"synchronized",
			"this",
			"throw",
			"throws",
			"transient",
			"try",
			"void",
			"volatile",
			"while",
			"true",
			"false",
			"null",
		)

	/**
	 * The first segment of [className] that Java will not accept as an identifier, if any.
	 *
	 * A proxy source is emitted as raw Java identifiers, so a segment like this produces a file
	 * javac cannot parse: `package com.example.native` is legal Kotlin, legal in a manifest
	 * `android:name`, and a syntax error in the `extends` clause and the package declaration the
	 * generator writes. Caught before the proxies are compiled, the build says which component is
	 * at fault and what the user can do instead; caught by javac, it says "<identifier> expected".
	 *
	 * @param className a fully qualified class name, or any dotted name.
	 * @return the offending segment, or null when every segment is a legal Java identifier.
	 */
	fun reservedJavaSegment(className: String): String? = className.split('.').firstOrNull { it in JAVA_RESERVED_WORDS }

	/**
	 * Emits the proxy source for [component]; the Application entry has no proxy.
	 *
	 * @param component one entry of the manifest transform's component list, whose `proxyClass`
	 *   must already be assigned.
	 * @return the complete `.java` source, package declaration included.
	 * @throws IllegalArgumentException if [component] carries no proxy class, or is the
	 *   Application entry.
	 */
	fun generateSource(component: ProxiedComponent): String {
		val proxyClass =
			requireNotNull(component.proxyClass) {
				"component '${component.userClass}' of type ${component.type} has no proxy class"
			}
		return generateSource(proxyClass, component.userClass, component.type)
	}

	/**
	 * Emits the proxy source for one class pair.
	 *
	 * @param proxyClass fully-qualified proxy class name (must contain a package).
	 * @param userClass fully-qualified user class the proxy extends, rewritten from a binary name
	 *   (`Outer$Inner`) to its canonical form for the extends clause when it is nested.
	 * @param type which component body to emit; only an activity gets one.
	 * @return the complete `.java` source, package declaration included.
	 * @throws IllegalArgumentException if [proxyClass] has no package, or [type] is
	 *   [ComponentType.APPLICATION].
	 */
	fun generateSource(
		proxyClass: String,
		userClass: String,
		type: ComponentType = ComponentType.ACTIVITY,
	): String {
		require('.' in proxyClass) { "proxy class '$proxyClass' has no package" }
		val packageName = proxyClass.substringBeforeLast('.')
		val simpleName = proxyClass.substringAfterLast('.')
		// A nested user class arrives as a BINARY name (Outer$Inner); a Java source
		// `extends` clause needs the CANONICAL name (Outer.Inner), so map '$' to '.'.
		// Proxy names are flat generated identifiers and never carry '$'.
		val userSourceName = userClass.replace('$', '.')
		return buildString {
			append("package ").append(packageName).append(";\n")
			append('\n')
			append("/**\n")
			append(" * Generated by CoGo Quick Build (ADFA-4128). Gives the manifest a stable component\n")
			append(" * name while the user's class stays swappable: proxy and superclass both\n")
			append(" * travel in the payload dex, so a hot reload swaps them together.\n")
			append(" */\n")
			append("public class ")
				.append(simpleName)
				.append(" extends ")
				.append(userSourceName)
				.append(" {\n")
			when (type) {
				ComponentType.ACTIVITY -> {
					appendActivityBody()
				}

				ComponentType.SERVICE, ComponentType.RECEIVER, ComponentType.PROVIDER -> {
					Unit
				}

				ComponentType.APPLICATION -> {
					throw IllegalArgumentException("the Application gets no proxy")
				}
			}
			append("}\n")
		}
	}

	/** Appends the activity-only member: the getClassLoader() override. */
	private fun StringBuilder.appendActivityBody() {
		append('\n')
		append("\t/**\n")
		append("	 * Context#getClassLoader() is otherwise fixed to the base APK's\n")
		append("\t * classloader regardless of which loader instantiated this activity, so\n")
		append("\t * by-name resolution (LayoutInflater custom views, FragmentFactory/Navigation\n")
		append("\t * destinations) can never see a payload-only class without this override.\n")
		append("\t */\n")
		append("\t@Override\n")
		append("\tpublic ClassLoader getClassLoader() {\n")
		append("\t\treturn ").append(CLASS_LOADERS_CLASS).append(".forActivity(super.getClassLoader());\n")
		append("\t}\n")
	}
}
