#!/bin/bash
#
# updateClaude.sh
#
# Runs unit tests + JaCoCo coverage report for the 4 covered modules,
# then regenerates CLAUDE.md at the project root with current test counts
# and coverage numbers for the next Claude Code session.
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

export JAVA_HOME=/home/yaturner/.jdk17
export PATH=$JAVA_HOME/bin:$PATH

echo "=== Running unit tests + coverage report ==="
cd "$PROJECT_ROOT"

./gradlew \
  :git-core:testV8DebugUnitTest \
  :common:testV8DebugUnitTest \
  :app:testV8DebugUnitTest \
  :lsp:indexing:testV8DebugUnitTest \
  jacocoUnitTestCoverageReport

echo ""
echo "=== Generating CLAUDE.md ==="

python3 - <<'PYEOF'
import xml.etree.ElementTree as ET
import os, datetime

project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
xml_path = os.path.join(project_root, "build/reports/jacoco/unitTestCoverage/coverage.xml")

tree = ET.parse(xml_path)
root = tree.getroot()

def pkg_coverage(prefixes):
    cov, tot = 0, 0
    for pkg in root.findall('package'):
        pname = pkg.get('name', '')
        if any(pname.startswith(p) for p in prefixes):
            for cls in pkg.findall('class'):
                for c in cls.findall('counter'):
                    if c.get('type') == 'INSTRUCTION':
                        cov += int(c.get('covered', 0))
                        tot += int(c.get('covered', 0)) + int(c.get('missed', 0))
    pct = (cov / tot * 100) if tot > 0 else 0
    return pct, cov, tot

def cls_coverage(class_name):
    for pkg in root.findall('package'):
        for cls in pkg.findall('class'):
            if cls.get('name', '') == class_name:
                for c in cls.findall('counter'):
                    if c.get('type') == 'INSTRUCTION':
                        cov = int(c.get('covered', 0))
                        mis = int(c.get('missed', 0))
                        tot = cov + mis
                        pct = (cov / tot * 100) if tot > 0 else 0
                        return pct, cov, tot
    return 0.0, 0, 0

modules = {
    'git-core':    ['com/itsaky/androidide/git/core'],
    'common':      ['com/itsaky/androidide/utils/KeyedDebouncingAction'],
    'app':         ['com/itsaky/androidide/utils/DiagnosticsFormatter'],
    'lsp:indexing':['org/appdevforall/codeonthego/indexing'],
}

overall_cov, overall_tot = 0, 0
for counter in root.findall('counter'):
    if counter.get('type') == 'INSTRUCTION':
        overall_cov = int(counter.get('covered', 0))
        overall_tot = overall_cov + int(counter.get('missed', 0))
overall_pct = (overall_cov / overall_tot * 100) if overall_tot > 0 else 0

now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M')

lines = []
lines.append(f"# CLAUDE.md — CodeOnTheGo Project Context")
lines.append(f"")
lines.append(f"_Auto-generated by `scripts/updateClaude.sh` on {now}_")
lines.append(f"")
lines.append(f"## Project")
lines.append(f"")
lines.append(f"**CodeOnTheGo** is an Android IDE (fork of AndroidIDE) targeting Kotlin/Java development on Android devices.")
lines.append(f"Multi-module Gradle project with V7 (32-bit) and V8 (64-bit) build flavors.")
lines.append(f"Active branch: `ADFA-4484-create-test-suites`")
lines.append(f"")
lines.append(f"## Build Environment")
lines.append(f"")
lines.append(f"- **JDK 17** required — Adoptium at `~/.jdk17`")
lines.append(f"- All `./gradlew` commands need: `JAVA_HOME=/home/yaturner/.jdk17 PATH=/home/yaturner/.jdk17/bin:$PATH`")
lines.append(f"- Use **V8 flavor** for development and testing")
lines.append(f"- Modules excluded from most builds: `:agent` (broken deps), `:subprojects:tooling-api-impl` (compile error)")
lines.append(f"")
lines.append(f"## Test Suite")
lines.append(f"")
lines.append(f"See **`TEST_SUITE.md`** at project root for full documentation of all tests.")
lines.append(f"")
lines.append(f"### Unit Tests (4 modules)")
lines.append(f"")
lines.append(f"```")
lines.append(f"# Run all 4 covered modules:")
lines.append(f"JAVA_HOME=/home/yaturner/.jdk17 PATH=/home/yaturner/.jdk17/bin:$PATH ./gradlew \\")
lines.append(f"  :git-core:testV8DebugUnitTest \\")
lines.append(f"  :common:testV8DebugUnitTest \\")
lines.append(f"  :app:testV8DebugUnitTest \\")
lines.append(f"  :lsp:indexing:testV8DebugUnitTest")
lines.append(f"```")
lines.append(f"")
lines.append(f"| Module | Tests | Key Classes |")
lines.append(f"|--------|-------|-------------|")
lines.append(f"| `:git-core` | 18 + 25 = 43 | GitRepositoryUrlsTest, GitModelsTest |")
lines.append(f"| `:common` | 10 | KeyedDebouncingActionTest |")
lines.append(f"| `:app` | 19 | DiagnosticsFormatterTest |")
lines.append(f"| `:lsp:indexing` | 10 + 18 = 28 | BackgroundIndexerTest, IndexQueryBuilderTest |")
lines.append(f"| **Total** | **100** | |")
lines.append(f"")
lines.append(f"### UI / Instrumentation Tests")
lines.append(f"")
lines.append(f"14 test classes (pre-existing). Run with:")
lines.append(f"```")
lines.append(f"JAVA_HOME=/home/yaturner/.jdk17 PATH=/home/yaturner/.jdk17/bin:$PATH ./gradlew :app:connectedV8DebugAndroidTest")
lines.append(f"```")
lines.append(f"Requires a connected Android device/emulator.")
lines.append(f"")
lines.append(f"## JaCoCo Coverage (as of {now})")
lines.append(f"")
lines.append(f"```")
lines.append(f"# Run tests + coverage in one invocation:")
lines.append(f"JAVA_HOME=/home/yaturner/.jdk17 PATH=/home/yaturner/.jdk17/bin:$PATH ./gradlew \\")
lines.append(f"  :git-core:testV8DebugUnitTest :common:testV8DebugUnitTest \\")
lines.append(f"  :app:testV8DebugUnitTest :lsp:indexing:testV8DebugUnitTest \\")
lines.append(f"  jacocoUnitTestCoverageReport")
lines.append(f"```")
lines.append(f"")
lines.append(f"Report output: `build/reports/jacoco/unitTestCoverage/html/index.html`")
lines.append(f"")
lines.append(f"### Per-Module Coverage (Instruction)")
lines.append(f"")

for mod, prefixes in modules.items():
    pct, cov, tot = pkg_coverage(prefixes)
    bar = '█' * int(pct / 5) + '░' * (20 - int(pct / 5))
    lines.append(f"- **`:{mod}`**: {pct:.1f}% `{bar}` ({cov}/{tot} instructions)")

lines.append(f"")
lines.append(f"### Key Class Coverage")
lines.append(f"")
key_classes = [
    ('GitRepositoryUrlsKt', 'com/itsaky/androidide/git/core/GitRepositoryUrlsKt'),
    ('GitStatus',           'com/itsaky/androidide/git/core/models/GitStatus'),
    ('GitCommit',           'com/itsaky/androidide/git/core/models/GitCommit'),
    ('GitBranch',           'com/itsaky/androidide/git/core/models/GitBranch'),
    ('FileChange',          'com/itsaky/androidide/git/core/models/FileChange'),
    ('DiagnosticsFormatter','com/itsaky/androidide/utils/DiagnosticsFormatter'),
    ('KeyedDebouncingAction','com/itsaky/androidide/utils/KeyedDebouncingAction'),
    ('InMemoryIndex',       'org/appdevforall/codeonthego/indexing/InMemoryIndex'),
    ('IndexQuery',          'org/appdevforall/codeonthego/indexing/api/IndexQuery'),
    ('IndexQueryBuilder',   'org/appdevforall/codeonthego/indexing/api/IndexQueryBuilder'),
    ('BackgroundIndexer',   'org/appdevforall/codeonthego/indexing/util/BackgroundIndexer'),
]
lines.append(f"| Class | Instructions |")
lines.append(f"|-------|-------------|")
for name, cls in key_classes:
    pct, cov, tot = cls_coverage(cls)
    note = " ⚠ mismatch (see below)" if name == 'DiagnosticsFormatter' and pct == 0 and tot > 0 else ""
    lines.append(f"| `{name}` | {pct:.1f}% ({cov}/{tot}){note} |")

lines.append(f"")
lines.append(f"### Known Issue: DiagnosticsFormatter Shows 0%")
lines.append(f"")
lines.append(f"`DiagnosticsFormatter` in `:app` always reports 0% due to a JaCoCo fingerprint mismatch — not an actual coverage gap.")
lines.append(f"Its inner lambdas report 100%, confirming the 19 DiagnosticsFormatterTest tests do execute.")
lines.append(f"")
lines.append(f"**Root cause:** The `app` module uses AGP offline JaCoCo instrumentation (`transformV8DebugClassesWithAsm`).")
lines.append(f"KAPT stub generation runs between production compilation and the ASM transform, triggering incremental")
lines.append(f"recompilation of some app classes. The exec file records the CRC of the pre-recompile bytecode; the")
lines.append(f"report reads the post-recompile class on disk → CRC mismatch → 0%.")
lines.append(f"")
lines.append(f"Library modules (`:git-core`, `:common`, `:lsp:indexing`) are unaffected.")
lines.append(f"")
lines.append(f"## Key Files")
lines.append(f"")
lines.append(f"| File | Purpose |")
lines.append(f"|------|---------|")
lines.append(f"| `TEST_SUITE.md` | Full test documentation — unit tests with per-test descriptions, UI tests |")
lines.append(f"| `build.gradle.kts` | Root build — JaCoCo config, `jacocoUnitTestCoverageReport` task, `jacocoAggregateReport` task |")
lines.append(f"| `app/build.gradle.kts` | App module — `enableUnitTestCoverage = true` in debug build type |")
lines.append(f"| `scripts/updateClaude.sh` | Re-runs tests + coverage and regenerates this file |")

output = "\n".join(lines) + "\n"
claude_md_path = os.path.join(project_root, "CLAUDE.md")
with open(claude_md_path, 'w') as f:
    f.write(output)
print(f"Written: {claude_md_path}")
PYEOF

echo ""
echo "=== Done ==="
echo "CLAUDE.md updated at project root."
echo "HTML report: build/reports/jacoco/unitTestCoverage/html/index.html"
