# Web Server Configuration

# The port number the server will listen on (default: 8080)
port = 8081

# The absolute path to the document root directory for serving static files
document_root = "/home/eisen/src/kotlin-web-server/static"

# The absolute path to the SQLite database file
sqlite_db_path = "/home/eisen/src/kotlin-web-server/data/content.db" 