name: Build Universal APK
permissions:
  contents: read
  actions: write
on:
  pull_request:
    branches: [ "stage", "feature/**" ]
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - '.github/workflows/crowdin_contributors.yml'
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Signing info (if needed)
  IDE_SIGNING_ALIAS: ${{ secrets.IDE_SIGNING_ALIAS }}
  IDE_SIGNING_AUTH_PASS: ${{ secrets.IDE_SIGNING_AUTH_PASS }}
  IDE_SIGNING_AUTH_USER: ${{ secrets.IDE_SIGNING_AUTH_USER }}
  IDE_SIGNING_KEY_PASS: ${{ secrets.IDE_SIGNING_KEY_PASS }}
  IDE_SIGNING_STORE_PASS: ${{ secrets.IDE_SIGNING_STORE_PASS }}
  IDE_SIGNING_URL: ${{ secrets.IDE_SIGNING_URL }}
  IDE_SIGNING_KEY_BIN: ${{ secrets.IDE_SIGNING_KEY_BIN }}
  # Publishing credentials (if needed)
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MVN_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MVN_PASSWORD }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MVN_SIGNING_KEY }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.MVN_SIGNING_KEY_ID }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MVN_SIGNING_KEY_PASSWORD }}
  # Build configuration
  BUILD_JAVA_VERSION: '17'
  BUILD_JAVA_DIST: 'temurin'

jobs:
  build_apk:
    name: Build Universal APK
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.BUILD_JAVA_VERSION }}
          distribution: ${{ env.BUILD_JAVA_DIST }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: "30"
          build-tools-version: "30.0.3"
          components: "platform-tools, build-tools;30.0.3, platforms;android-30"

      - name: Initialize submodules
        run: |
          git submodule init
          git submodule update --remote

      # Fix for LayoutEditor directory case sensitivity
      - name: Create symbolic link for LayoutEditor
        run: |
          if [ -d "$GITHUB_WORKSPACE/LayoutEditor" ] && [ ! -d "$GITHUB_WORKSPACE/layouteditor" ]; then
            ln -sf "$GITHUB_WORKSPACE/LayoutEditor" "$GITHUB_WORKSPACE/layouteditor"
            echo "Created symbolic link: layouteditor -> LayoutEditor"
          elif [ -d "$GITHUB_WORKSPACE/LayoutEditor" ] && [ -d "$GITHUB_WORKSPACE/layouteditor" ]; then
            echo "Both directories exist, ensuring layouteditor is linked to LayoutEditor"
            rm -rf "$GITHUB_WORKSPACE/layouteditor"
            ln -sf "$GITHUB_WORKSPACE/LayoutEditor" "$GITHUB_WORKSPACE/layouteditor"
          else
            echo "LayoutEditor directory not found"
            exit 1
          fi

      - name: Restore Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Assemble Universal APK
        run: ./gradlew clean :app:assembleDebug --no-daemon --stacktrace

      - name: Copy APK Artifact
        run: cp app/build/outputs/apk/debug/CodeOnTheGo-*.apk universal.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: universal-apk
          path: universal.apk
