name: Build APK
permissions:
  contents: write
  actions: write
on:
  pull_request:
    branches: [ "stage", "feature/**" ]
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - '.github/workflows/crowdin_contributors.yml'
  workflow_dispatch: { }

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Signing info (if needed)
  IDE_SIGNING_ALIAS: ${{ secrets.IDE_SIGNING_ALIAS }}
  IDE_SIGNING_AUTH_PASS: ${{ secrets.IDE_SIGNING_AUTH_PASS }}
  IDE_SIGNING_AUTH_USER: ${{ secrets.IDE_SIGNING_AUTH_USER }}
  IDE_SIGNING_KEY_PASS: ${{ secrets.IDE_SIGNING_KEY_PASS }}
  IDE_SIGNING_STORE_PASS: ${{ secrets.IDE_SIGNING_STORE_PASS }}
  IDE_SIGNING_URL: ${{ secrets.IDE_SIGNING_URL }}
  IDE_SIGNING_KEY_BIN: ${{ secrets.IDE_SIGNING_KEY_BIN }}
  # Publishing credentials (if needed)
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MVN_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MVN_PASSWORD }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MVN_SIGNING_KEY }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.MVN_SIGNING_KEY_ID }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MVN_SIGNING_KEY_PASSWORD }}
  # Build configuration
  BUILD_JAVA_VERSION: '17'
  BUILD_JAVA_DIST: 'temurin'

jobs:
  build_apk:
    name: Build Universal APK
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Setup Git LFS
        run: |
          echo "Setting up Git LFS"
          where git-lfs || (
            echo "Installing Git LFS"
            powershell -Command "Invoke-WebRequest -Uri https://github.com/git-lfs/git-lfs/releases/download/v3.4.1/git-lfs-windows-amd64-v3.4.1.zip -OutFile git-lfs.zip; Expand-Archive -Path git-lfs.zip -DestinationPath git-lfs; cd git-lfs; .\git-lfs-3.4.1\install.bat"
          )
          git lfs install
        shell: cmd

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Pull Git LFS Files
        run: git lfs pull
        shell: cmd

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.BUILD_JAVA_VERSION }}
          distribution: ${{ env.BUILD_JAVA_DIST }}

      - name: Initialize Submodules
        run: |
          git submodule init
          git submodule update --remote
        shell: cmd

      - name: Restore Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Extract Commit Message
        id: extract_commit_message
        run: |
          for /f "tokens=*" %%a in ('git log -1 --pretty=format:"%%B"') do (
            set "COMMIT_MESSAGE=%%a"
          )
          echo Commit Message: %COMMIT_MESSAGE%
          echo COMMIT_MESSAGE=%COMMIT_MESSAGE% >> %GITHUB_ENV%
        shell: cmd

      - name: Assemble Universal APK
        id: build_apk
        run: |
          .\gradlew.bat assembleDebug
          if %errorlevel% neq 0 exit /b %errorlevel%
        shell: cmd

      - name: Extract Branch Information
        id: extract_branch
        run: |
          @echo off
          rem Use the head ref for PR events; otherwise, fallback to the branch name
          if defined GITHUB_HEAD_REF (
            set "BRANCH_NAME=%GITHUB_HEAD_REF%"
          ) else (
            set "BRANCH_NAME=%GITHUB_REF:refs/heads/=%"
          )
          echo Branch: %BRANCH_NAME%
          
          rem Extract Jira ticket pattern using PowerShell
          powershell -Command "$branch = '%BRANCH_NAME%'; $match = [regex]::Match($branch, '[A-Z]+-[0-9]+'); if($match.Success) { $folder = $match.Value } else { $folder = '%BRANCH_NAME%' }; Write-Output \"Folder Name: $folder\"; \"FOLDER_NAME=$folder\" | Out-File -Append $env:GITHUB_ENV"
        shell: cmd

      - name: Install rclone
        run: |
          echo Installing rclone...
          powershell -Command "Invoke-WebRequest -Uri 'https://downloads.rclone.org/rclone-current-windows-amd64.zip' -OutFile 'rclone.zip'"
          powershell -Command "Expand-Archive -Path 'rclone.zip' -DestinationPath '.\\rclone'"
          for /d %%i in (.\rclone\rclone-*-windows-amd64) do (
            set "RCLONE_DIR=%%i"
          )
          echo RCLONE_DIR is %RCLONE_DIR%
          set "RCLONE_PATH=%CD%\%RCLONE_DIR%\rclone.exe"
          echo RCLONE_PATH=%RCLONE_PATH% >> %GITHUB_ENV%
        shell: cmd

      - name: Configure rclone for Google Drive
        env:
          COGO_SERVICE_ACCOUNT: ${{ secrets.COGO_SERVICE_ACCOUNT }}
        run: |
          powershell -Command "Set-Content -Path 'gdrive-service-account.json' -Value $env:COGO_SERVICE_ACCOUNT"
          "%RCLONE_PATH%" config create google-drive drive scope drive service_account_file gdrive-service-account.json
        shell: cmd

      - name: Upload APK to Google Drive and Get Download Link
        id: upload_and_link
        run: |
          @echo off
          rem Find APK file
          for /f "tokens=*" %%a in ('powershell -Command "Get-ChildItem -Path . -Recurse -Filter CodeOnTheGo-*.apk -File | Select-Object -First 1 -ExpandProperty FullName"') do (
            set "APK_PATH=%%a"
          )
          
          if not defined APK_PATH (
            echo Error: No APK file found
            exit /b 1
          )
          
          echo Found APK: %APK_PATH%
          
          rem Upload to Google Drive folder
          "%RCLONE_PATH%" copy "%APK_PATH%" google-drive:"%FOLDER_NAME%" -v
          
          if %errorlevel% neq 0 (
            echo Error uploading APK to Google Drive
            exit /b %errorlevel%
          )
          
          rem Find APK filename
          for /f "tokens=*" %%a in ('powershell -Command "Get-ChildItem -Path . -Recurse -Filter CodeOnTheGo-*.apk -File | Select-Object -First 1 -ExpandProperty Name"') do (
            set "APK_FILENAME=%%a"
          )
          
          set "APK_PATH_IN_GDRIVE=%FOLDER_NAME%/%APK_FILENAME%"
          
          rem Get and set download link
          for /f "tokens=*" %%a in ('"%RCLONE_PATH%" link "google-drive:%APK_PATH_IN_GDRIVE%"') do (
            set "DOWNLOAD_URL=%%a"
          )
          
          echo APK Download URL: %DOWNLOAD_URL%
          echo DOWNLOAD_URL=%DOWNLOAD_URL% >> %GITHUB_ENV%
        shell: cmd

#      - name: Slack Notification
#        run: |
#          @echo off
#          rem Prepare dynamic message blocks
#          set "TICKET_URL=https://appdevforall.atlassian.net/browse/%FOLDER_NAME%"
#
#          rem Ensure DOWNLOAD_URL has a fallback
#          if not defined DOWNLOAD_URL (
#            set "DOWNLOAD_URL=Download link unavailable"
#          )
#
#          rem Create JSON payload with rich Slack message
#          set "PAYLOAD={\"blocks\":[{\"type\":\"header\",\"text\":{\"type\":\"plain_text\",\"text\":\":rocket: APK Build Completed\",\"emoji\":true}},{\"type\":\"section\",\"fields\":[{\"type\":\"mrkdwn\",\"text\":\"*Branch:*\n%FOLDER_NAME%\"},{\"type\":\"mrkdwn\",\"text\":\"*Commit Message:*\n%COMMIT_MESSAGE:~0,100%\"}]},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Download Links:*\n• APK: %DOWNLOAD_URL%\n• Jira Ticket: %TICKET_URL%\"}},{\"type\":\"context\",\"elements\":[{\"type\":\"mrkdwn\",\"text\":\":information_source: Build completed successfully\"}]}]}"
#
#          rem Escape the payload for PowerShell
#          powershell -Command "$payload = '%PAYLOAD%'; $body = $payload | ConvertFrom-Json; Invoke-RestMethod -Uri 'https://hooks.slack.com/services/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' -Method Post -Body ($body | ConvertTo-Json -Depth 10) -ContentType 'application/json'"
#        shell: cmd
#
#      - name: Failure Notification
#        if: failure()
#        run: |
#          @echo off
#          set "ERROR_MESSAGE={\"blocks\":[{\"type\":\"header\",\"text\":{\"type\":\"plain_text\",\"text\":\":warning: Build Failed\",\"emoji\":true}},{\"type\":\"section\",\"fields\":[{\"type\":\"mrkdwn\",\"text\":\"*Workflow:* ${{ github.job }}\"}]},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Repository:* ${{ github.repository }}\n*Branch:* ${{ github.ref_name }}\"}},{\"type\":\"context\",\"elements\":[{\"type\":\"mrkdwn\",\"text\":\":x: Workflow encountered an error\"}]}]}"
#
#          powershell -Command "$message = '%ERROR_MESSAGE%'; $body = $message | ConvertFrom-Json; Invoke-RestMethod -Uri 'https://hooks.slack.com/services/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' -Method Post -Body ($body | ConvertTo-Json -Depth 10) -ContentType 'application/json'"
#        shell: cmd