name: Run Android UI Tests with cAT

permissions:
  contents: read
  actions: write

on:
  pull_request:
    branches: [ "stage", "feature/**" ]
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - '.github/workflows/crowdin_contributors.yml'
      - '.github/workflows/deploy-to-firestore-app-distribution.yml'
  workflow_dispatch: { }

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BUILD_JAVA_VERSION: '17'
  BUILD_JAVA_DIST: 'temurin'

jobs:
  run_ui_tests:
    name: Run UI Tests with cAT
    runs-on: self-hosted
    timeout-minutes: 120

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install and Configure Git LFS - Selective pull
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install
          git lfs pull

      - name: Fetch Git LFS objects
        run: git lfs pull

      - name: Initialize submodules
        run: |
          git submodule init
          git submodule update --remote

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.BUILD_JAVA_VERSION }}
          distribution: ${{ env.BUILD_JAVA_DIST }}

      - name: Restore Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Install KVM dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-clients libvirt-daemon-system qemu-kvm bridge-utils
          sudo systemctl enable libvirtd
          sudo systemctl start libvirtd
          ls -la /dev/kvm || echo "KVM device not found"
          groups $(whoami)
          sudo usermod -aG kvm $(whoami)
          sudo chmod 666 /dev/kvm || echo "Cannot chmod /dev/kvm"
          # Ensure current session has kvm group access
          if [ $(stat -c '%G' /dev/kvm) = "kvm" ]; then
            sudo chgrp kvm /dev/kvm
            newgrp kvm
          fi

      - name: Clean AVD folder
        run: |
          rm -rf ~/.android/avd/*
          mkdir -p ~/.android/avd/

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      # Install required SDK components
      - name: Install required SDK components
        run: |
          sdkmanager "platform-tools" "platforms;android-29" "build-tools;30.0.3" "system-images;android-29;default;x86_64" "emulator"
          echo "SDK components installed"

      # Verify emulator installation
      - name: Verify emulator installation
        run: |
          ls -la $ANDROID_SDK_ROOT/emulator/
          $ANDROID_SDK_ROOT/emulator/emulator -version

      # Create AVD with more memory and ensure it's created properly
      - name: Create AVD manually
        run: |
          echo "Creating AVD manually"
          echo "no" | avdmanager create avd -n test -k "system-images;android-29;default;x86_64" -c 2000M -f
          ls -la ~/.android/avd/
          cat ~/.android/avd/test.avd/config.ini

      # Add memory parameters to config
      - name: Configure emulator settings
        run: |
          echo "hw.ramSize=2048" >> ~/.android/avd/test.avd/config.ini
          echo "vm.heapSize=512" >> ~/.android/avd/test.avd/config.ini
          echo "disk.dataPartition.size=4096M" >> ~/.android/avd/test.avd/config.ini

      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          avd-name: test
          force-avd-creation: false  # We created it manually above
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader -noaudio -no-boot-anim -memory 2048
          disable-animations: true
          script: |
            # Wait for device to be fully booted
            adb wait-for-device
            adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 3; done'
            
            # Show connected devices
            adb devices
            
            # Run instrumentation tests
            ./gradlew app:connectedDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.itsaky.androidide.OrderedTestSuite

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: instrumentation-test-results
          path: app/build/reports/androidTests/connected/