name: Run Android UI Tests with cAT

permissions:
  contents: read
  actions: write

on:
  pull_request:
    branches: [ "stage", "feature/**" ]
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
  workflow_dispatch: {}

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BUILD_JAVA_VERSION: '17'
  BUILD_JAVA_DIST: 'temurin'
  IDE_SIGNING_ALIAS: ${{ secrets.IDE_SIGNING_ALIAS }}
  IDE_SIGNING_AUTH_PASS: ${{ secrets.IDE_SIGNING_AUTH_PASS }}
  IDE_SIGNING_AUTH_USER: ${{ secrets.IDE_SIGNING_AUTH_USER }}
  IDE_SIGNING_KEY_PASS: ${{ secrets.IDE_SIGNING_KEY_PASS }}
  IDE_SIGNING_STORE_PASS: ${{ secrets.IDE_SIGNING_STORE_PASS }}
  IDE_SIGNING_URL: ${{ secrets.IDE_SIGNING_URL }}
  IDE_SIGNING_KEY_BIN: ${{ secrets.IDE_SIGNING_KEY_BIN }}
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MVN_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MVN_PASSWORD }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MVN_SIGNING_KEY }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.MVN_SIGNING_KEY_ID }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MVN_SIGNING_KEY_PASSWORD }}

jobs:
  run_ui_tests:
    name: Run UI Tests with cAT
    runs-on: self-hosted
    timeout-minutes: 120

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install and Configure Git LFS - Selective pull
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install
          git lfs pull

      - name: Initialize submodules
        run: |
          git submodule init
          git submodule update --remote

      - name: Set up JDKs
        uses: actions/setup-java@v4
        with:
          cache: 'gradle'
          distribution: temurin
          java-version: |
            8
            17

      - name: Set Java_ROOT environment variable
        run: echo "Java_ROOT=$JAVA_HOME_8_X64" >> $GITHUB_ENV

      - name: Restore Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required Android SDK components
        run: sdkmanager "platforms;android-34" "build-tools;34.0.0" "system-images;android-34;google_apis;x86_64" "cmake;3.31.4"

      - name: Verify CMake version
        run: |
          cmake --version
          which cmake

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Install KVM dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-clients libvirt-daemon-system qemu-kvm bridge-utils
          sudo systemctl enable libvirtd
          sudo systemctl start libvirtd
          ls -la /dev/kvm || echo "KVM device not found"
          groups $(whoami)
          sudo usermod -aG kvm $(whoami)
          sudo chmod 666 /dev/kvm || echo "Cannot chmod /dev/kvm"

      - name: Clean AVD folder
        run: |
          rm -rf ~/.android/avd/*
          mkdir -p ~/.android/avd/

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Free up disk space
        run: |
          echo "Disk space before cleanup:"
          df -h
          echo "Cleaning Android SDK cache..."
          rm -rf "${ANDROID_HOME}/temp/" || true
          echo "Removing unused system images..."
          find "${ANDROID_HOME}/system-images" -mindepth 1 -maxdepth 1 -type d -not -name "android-34" | xargs rm -rf || true
          echo "Cleaning Gradle cache..."
          rm -rf ~/.gradle/caches/transforms-*
          rm -rf ~/.gradle/caches/*/fileHashes/
          rm -rf ~/.gradle/caches/*/javaCompile/
          echo "Removing Android build directories..."
          find . -name "build" -type d -exec rm -rf {} +
          echo "Disk space after cleanup:"
          df -h

      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        timeout-minutes: 20
        with:
            api-level: 34
            target: google_apis
            arch: x86_64
            avd-name: Pixel_9
            device: pixel
            force-avd-creation: true
            emulator-options: -no-snapshot-save -no-window -gpu swiftshader -noaudio -no-boot-anim
            disable-animations: true
            script: |
              echo "Waiting for emulator to start..."
              adb wait-for-device
              adb devices
              echo "Emulator ready, setting properties..."
              adb shell settings put global window_animation_scale 0
              adb shell settings put global transition_animation_scale 0
              adb shell settings put global animator_duration_scale 0
              echo "Running tests..."
              ./gradlew app:cAT -Pandroid.testInstrumentationRunnerArguments.class=com.itsaky.androidide.OrderedTestSuite --stacktrace